### ISSUE TITLE
Wrong return code for cypress run on Mac

### ISSUE THREAD

**Issue by shauvik** [cypress-io/cypress-cli#9] opened 2016-06-06 19:11 UTC
`cypress run` exits with a **0** return code even for failing tests on Mac OS X.

Example :
```
 24 passing (4m)
  1 pending
  5 failing
```
```
$ echo $?
0
```

This is not a problem with `cypress ci` on linux at least.

**Comment by brian-mann** [comment] 2016-06-13 16:50
This actually is/was the intended behavior but we'll change this in the next release.

**Comment by brian-mann** [comment] 2016-06-17 15:03
Fixed in [`0.16.3`](https://github.com/cypress-io/cypress/wiki/Changelog#0163-06172016).

**Closed by brian-mann** 2016-06-17 15:03 UTC
Labels: bug
